name: Build
on:
  push:
    branches:
      - master
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Setup node
        uses: actions/setup-node@v2.0.0
        with:
          node-version: '12.x'
      - name: Install project
        run: npm ci --ignore-scripts
      - name: Build
        run: npm run build
