name: Lint
on:
  push:
    branches:
      - master
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Setup node
        uses: actions/setup-node@v2.0.0
        with:
          node-version: '12.x'
      - name: Install project
        run: npm ci --ignore-scripts
      - name: Lint
        run: npm run lint
      - name: Check formatting
        run: npm run format:check
